# Secrets for all airflow containers
secret:
  - envName: "REDDIT_CLIENT_ID"
    secretName: "reddit-qdrant-secrets"
    secretKey: "REDDIT_CLIENT_ID"
  - envName: "REDDIT_CLIENT_SECRET"
    secretName: "reddit-qdrant-secrets"
    secretKey: "REDDIT_CLIENT_SECRET"
  - envName: "QDRANT_API_KEY"
    secretName: "reddit-qdrant-secrets"
    secretKey: "QDRANT_API_KEY"

# Git sync
dags:
  # Where dags volume will be mounted. Works for both persistence and gitSync.
  # If not specified, dags mount path will be set to $AIRFLOW_HOME/dags
  # mountPath: /opt/airflow/dags
  persistence:
    # Annotations for dags PVC
    annotations: {}
    # Enable persistent volume for storing dags
    enabled: false
    # Volume size for dags
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName:
    # access mode of the persistent volume
    accessMode: ReadWriteOnce
    ## the name of an existing PVC to use
    existingClaim:
    ## optional subpath for dag volume mount
    subPath: ~
  gitSync:
    enabled: True

    # git repo clone url
    # ssh example: git@github.com:apache/airflow.git
    # https example: https://github.com/apache/airflow.git
    repo: https://github.com/sarabesh/reddit-recsys.git
    branch: main
    # rev: HEAD
    # The git revision (branch, tag, or hash) to check out, v4 only
    # ref: v2-2-stable
    # depth: 1
    # the number of consecutive failures allowed before aborting
    maxFailures: 0
    # subpath within the repo where dags are located
    # should be "" if dags are at repo root
    subPath: "dags"
#     # if your repo needs a user name password
#     # you can load them to a k8s secret like the one below
#     #   ---
#     #   apiVersion: v1
#     #   kind: Secret
#     #   metadata:
#     #     name: git-credentials
#     #   data:
#     #     # For git-sync v3
#     #     GIT_SYNC_USERNAME: <base64_encoded_git_username>
#     #     GIT_SYNC_PASSWORD: <base64_encoded_git_password>
#     #     # For git-sync v4
#     #     GITSYNC_USERNAME: <base64_encoded_git_username>
#     #     GITSYNC_PASSWORD: <base64_encoded_git_password>
#     # and specify the name of the secret below
#     #
#     # credentialsSecret: git-credentials
#     #
#     #
#     # If you are using an ssh clone url, you can load
#     # the ssh private key to a k8s secret like the one below
#     #   ---
#     #   apiVersion: v1
#     #   kind: Secret
#     #   metadata:
#     #     name: airflow-ssh-secret
#     #   data:
#     #     # key needs to be gitSshKey
#     #     gitSshKey: <base64_encoded_data>
#     # and specify the name of the secret below
#     # sshKeySecret: airflow-ssh-secret
#     #
#     # Or set sshKeySecret with your key
#     # sshKey: |-
#     #   -----BEGIN {OPENSSH PRIVATE KEY}-----
#     #   ...
#     #   -----END {OPENSSH PRIVATE KEY}-----
#     #
#     # If you are using an ssh private key, you can additionally
#     # specify the content of your known_hosts file, example:
#     #
#     # knownHosts: |
#     #    <host1>,<ip1> <key1>
#     #    <host2>,<ip2> <key2>

#     # interval between git sync attempts in seconds
#     # high values are more likely to cause DAGs to become out of sync between different components
#     # low values cause more traffic to the remote git repository
#     # Go-style duration string (e.g. "100ms" or "0.1s" = 100ms).
#     # For backwards compatibility, wait will be used if it is specified.
#     period: 5s
#     wait: ~
#     # add variables from secret into gitSync containers, such proxy-config
#     envFrom: ~
#     # envFrom: |
#     #   - secretRef:
#     #       name: 'proxy-config'

#     containerName: git-sync
#     uid: 65533

#     # When not set, the values defined in the global securityContext will be used
#     securityContext: {}
#     #  runAsUser: 65533
#     #  runAsGroup: 0

#     securityContexts:
#       container: {}

#     # container level lifecycle hooks
#     containerLifecycleHooks: {}

#     # Mount additional volumes into git-sync. It can be templated like in the following example:
#     #   extraVolumeMounts:
#     #     - name: my-templated-extra-volume
#     #       mountPath: "{{ .Values.my_custom_path }}"
#     #       readOnly: true
#     extraVolumeMounts: []
#       # - name: local-dags
#       #   mountPath: /opt/airflow/dags
#       # - name: local-scripts
#       #   mountPath: /opt/airflow/dags/scripts
    
#     # extraVolumes: []
#     #   # - name: local-dags
#     #   #   hostPath:
#     #   #     path: Z:\projects\recsys1\dags
#     #   #     type: Directory
#     #   # - name: local-scripts
#     #   #   hostPath:
#     #   #     path: Z:\projects\recsys1\scripts
#     #   #     type: Directory

#     env: []
#     # Supported env vars for gitsync can be found at https://github.com/kubernetes/git-sync
#     # - name: ""
#     #   value: ""

#     # Configuration for empty dir volume
#     # emptyDirConfig:
#     #   sizeLimit: 1Gi
#     #   medium: Memory

#     resources: {}
#     #  limits:
#     #   cpu: 100m
#     #   memory: 128Mi
#     #  requests:
#     #   cpu: 100m
#     #   memory: 128Mi
